---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gibbons-tony
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-mlapi.yaml
images:
  - name: project
    newName: 650251712107.dkr.ecr.us-west-2.amazonaws.com/gibbons-tony/project
    newTag: "7781e3e"  # Using a git hash similar to lab4
