---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gibbons-tony
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-api.yaml
images:
  - name: lab4
    newName: 650251712107.dkr.ecr.us-west-2.amazonaws.com/gibbons-tony/lab
    newTag: "e798740"
