-- Create forward-filled continuous daily GDELT table
-- Purpose: Ensure every date has a record for each commodity (coffee, sugar)
-- Missing dates get: count columns = 0, tone columns = forward-filled from prior date

-- Drop table if exists
DROP TABLE IF EXISTS commodity.silver.gdelt_wide_fillforward;

-- Create forward-filled table
CREATE TABLE commodity.silver.gdelt_wide_fillforward
USING DELTA
AS
WITH date_spine AS (
  -- Get all dates from min to max in existing data
  SELECT EXPLODE(SEQUENCE(
    (SELECT MIN(article_date) FROM commodity.silver.gdelt_wide),
    (SELECT MAX(article_date) FROM commodity.silver.gdelt_wide),
    INTERVAL 1 DAY
  )) AS article_date
),
commodities AS (
  SELECT DISTINCT commodity FROM commodity.silver.gdelt_wide
),
complete_grid AS (
  -- Cross join to get all date-commodity combinations
  SELECT
    d.article_date,
    c.commodity
  FROM date_spine d
  CROSS JOIN commodities c
),
with_data AS (
  -- Left join with actual data
  SELECT
    g.article_date,
    g.commodity,

    -- Count columns: COALESCE to 0 for missing dates
    COALESCE(w.group_ALL_count, 0) AS group_ALL_count,
    COALESCE(w.group_CORE_count, 0) AS group_CORE_count,
    COALESCE(w.group_LOGISTICS_count, 0) AS group_LOGISTICS_count,
    COALESCE(w.group_MARKET_count, 0) AS group_MARKET_count,
    COALESCE(w.group_OTHER_count, 0) AS group_OTHER_count,
    COALESCE(w.group_POLICY_count, 0) AS group_POLICY_count,
    COALESCE(w.group_SUPPLY_count, 0) AS group_SUPPLY_count,
    COALESCE(w.group_TRADE_count, 0) AS group_TRADE_count,
    COALESCE(w.theme_AGRICULTURE_count, 0) AS theme_AGRICULTURE_count,
    COALESCE(w.theme_ALLIANCE_count, 0) AS theme_ALLIANCE_count,
    COALESCE(w.theme_DELAY_count, 0) AS theme_DELAY_count,
    COALESCE(w.theme_ECON_DEBT_count, 0) AS theme_ECON_DEBT_count,
    COALESCE(w.theme_ECON_INFLATION_count, 0) AS theme_ECON_INFLATION_count,
    COALESCE(w.theme_ECON_STOCKMARKET_count, 0) AS theme_ECON_STOCKMARKET_count,
    COALESCE(w.theme_ELECTION_count, 0) AS theme_ELECTION_count,
    COALESCE(w.theme_EPU_POLICY_count, 0) AS theme_EPU_POLICY_count,
    COALESCE(w.theme_EPU_POLICY_GOVERNMENT_count, 0) AS theme_EPU_POLICY_GOVERNMENT_count,
    COALESCE(w.theme_GENERAL_GOVERNMENT_count, 0) AS theme_GENERAL_GOVERNMENT_count,
    COALESCE(w.theme_LEGISLATION_count, 0) AS theme_LEGISLATION_count,
    COALESCE(w.theme_NATURAL_DISASTER_count, 0) AS theme_NATURAL_DISASTER_count,
    COALESCE(w.theme_TAX_DISEASE_count, 0) AS theme_TAX_DISEASE_count,
    COALESCE(w.theme_WB_698_TRADE_count, 0) AS theme_WB_698_TRADE_count,

    -- Tone columns: keep actual values (will forward-fill in next CTE)
    w.group_ALL_tone_avg,
    w.group_ALL_tone_positive,
    w.group_ALL_tone_negative,
    w.group_ALL_tone_polarity,
    w.group_CORE_tone_avg,
    w.group_LOGISTICS_tone_avg,
    w.group_MARKET_tone_avg,
    w.group_OTHER_tone_avg,
    w.group_POLICY_tone_avg,
    w.group_SUPPLY_tone_avg,
    w.group_TRADE_tone_avg,
    w.group_CORE_tone_negative,
    w.group_LOGISTICS_tone_negative,
    w.group_MARKET_tone_negative,
    w.group_OTHER_tone_negative,
    w.group_POLICY_tone_negative,
    w.group_SUPPLY_tone_negative,
    w.group_TRADE_tone_negative,
    w.group_CORE_tone_polarity,
    w.group_LOGISTICS_tone_polarity,
    w.group_MARKET_tone_polarity,
    w.group_OTHER_tone_polarity,
    w.group_POLICY_tone_polarity,
    w.group_SUPPLY_tone_polarity,
    w.group_TRADE_tone_polarity,
    w.group_CORE_tone_positive,
    w.group_LOGISTICS_tone_positive,
    w.group_MARKET_tone_positive,
    w.group_OTHER_tone_positive,
    w.group_POLICY_tone_positive,
    w.group_SUPPLY_tone_positive,
    w.group_TRADE_tone_positive,
    w.theme_AGRICULTURE_tone_avg,
    w.theme_ALLIANCE_tone_avg,
    w.theme_DELAY_tone_avg,
    w.theme_ECON_DEBT_tone_avg,
    w.theme_ECON_INFLATION_tone_avg,
    w.theme_ECON_STOCKMARKET_tone_avg,
    w.theme_ELECTION_tone_avg,
    w.theme_EPU_POLICY_tone_avg,
    w.theme_EPU_POLICY_GOVERNMENT_tone_avg,
    w.theme_GENERAL_GOVERNMENT_tone_avg,
    w.theme_LEGISLATION_tone_avg,
    w.theme_NATURAL_DISASTER_tone_avg,
    w.theme_TAX_DISEASE_tone_avg,
    w.theme_WB_698_TRADE_tone_avg,
    w.theme_AGRICULTURE_tone_negative,
    w.theme_ALLIANCE_tone_negative,
    w.theme_DELAY_tone_negative,
    w.theme_ECON_DEBT_tone_negative,
    w.theme_ECON_INFLATION_tone_negative,
    w.theme_ECON_STOCKMARKET_tone_negative,
    w.theme_ELECTION_tone_negative,
    w.theme_EPU_POLICY_tone_negative,
    w.theme_EPU_POLICY_GOVERNMENT_tone_negative,
    w.theme_GENERAL_GOVERNMENT_tone_negative,
    w.theme_LEGISLATION_tone_negative,
    w.theme_NATURAL_DISASTER_tone_negative,
    w.theme_TAX_DISEASE_tone_negative,
    w.theme_WB_698_TRADE_tone_negative,
    w.theme_AGRICULTURE_tone_polarity,
    w.theme_ALLIANCE_tone_polarity,
    w.theme_DELAY_tone_polarity,
    w.theme_ECON_DEBT_tone_polarity,
    w.theme_ECON_INFLATION_tone_polarity,
    w.theme_ECON_STOCKMARKET_tone_polarity,
    w.theme_ELECTION_tone_polarity,
    w.theme_EPU_POLICY_tone_polarity,
    w.theme_EPU_POLICY_GOVERNMENT_tone_polarity,
    w.theme_GENERAL_GOVERNMENT_tone_polarity,
    w.theme_LEGISLATION_tone_polarity,
    w.theme_NATURAL_DISASTER_tone_polarity,
    w.theme_TAX_DISEASE_tone_polarity,
    w.theme_WB_698_TRADE_tone_polarity,
    w.theme_AGRICULTURE_tone_positive,
    w.theme_ALLIANCE_tone_positive,
    w.theme_DELAY_tone_positive,
    w.theme_ECON_DEBT_tone_positive,
    w.theme_ECON_INFLATION_tone_positive,
    w.theme_ECON_STOCKMARKET_tone_positive,
    w.theme_ELECTION_tone_positive,
    w.theme_EPU_POLICY_tone_positive,
    w.theme_EPU_POLICY_GOVERNMENT_tone_positive,
    w.theme_GENERAL_GOVERNMENT_tone_positive,
    w.theme_LEGISLATION_tone_positive,
    w.theme_NATURAL_DISASTER_tone_positive,
    w.theme_TAX_DISEASE_tone_positive,
    w.theme_WB_698_TRADE_tone_positive

  FROM complete_grid g
  LEFT JOIN commodity.silver.gdelt_wide w
    ON g.article_date = w.article_date
    AND g.commodity = w.commodity
)
SELECT
  article_date,
  commodity,

  -- Count columns (already COALESCED to 0)
  group_ALL_count,
  group_CORE_count,
  group_LOGISTICS_count,
  group_MARKET_count,
  group_OTHER_count,
  group_POLICY_count,
  group_SUPPLY_count,
  group_TRADE_count,
  theme_AGRICULTURE_count,
  theme_ALLIANCE_count,
  theme_DELAY_count,
  theme_ECON_DEBT_count,
  theme_ECON_INFLATION_count,
  theme_ECON_STOCKMARKET_count,
  theme_ELECTION_count,
  theme_EPU_POLICY_count,
  theme_EPU_POLICY_GOVERNMENT_count,
  theme_GENERAL_GOVERNMENT_count,
  theme_LEGISLATION_count,
  theme_NATURAL_DISASTER_count,
  theme_TAX_DISEASE_count,
  theme_WB_698_TRADE_count,

  -- Tone columns: forward-fill using LAST_VALUE window function
  LAST_VALUE(group_ALL_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_avg,
  LAST_VALUE(group_ALL_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_positive,
  LAST_VALUE(group_ALL_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_negative,
  LAST_VALUE(group_ALL_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_polarity,
  LAST_VALUE(group_CORE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_avg,
  LAST_VALUE(group_LOGISTICS_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_avg,
  LAST_VALUE(group_MARKET_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_avg,
  LAST_VALUE(group_OTHER_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_avg,
  LAST_VALUE(group_POLICY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_avg,
  LAST_VALUE(group_SUPPLY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_avg,
  LAST_VALUE(group_TRADE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_avg,
  LAST_VALUE(group_CORE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_negative,
  LAST_VALUE(group_LOGISTICS_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_negative,
  LAST_VALUE(group_MARKET_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_negative,
  LAST_VALUE(group_OTHER_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_negative,
  LAST_VALUE(group_POLICY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_negative,
  LAST_VALUE(group_SUPPLY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_negative,
  LAST_VALUE(group_TRADE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_negative,
  LAST_VALUE(group_CORE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_polarity,
  LAST_VALUE(group_LOGISTICS_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_polarity,
  LAST_VALUE(group_MARKET_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_polarity,
  LAST_VALUE(group_OTHER_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_polarity,
  LAST_VALUE(group_POLICY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_polarity,
  LAST_VALUE(group_SUPPLY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_polarity,
  LAST_VALUE(group_TRADE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_polarity,
  LAST_VALUE(group_CORE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_positive,
  LAST_VALUE(group_LOGISTICS_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_positive,
  LAST_VALUE(group_MARKET_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_positive,
  LAST_VALUE(group_OTHER_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_positive,
  LAST_VALUE(group_POLICY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_positive,
  LAST_VALUE(group_SUPPLY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_positive,
  LAST_VALUE(group_TRADE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_positive,
  LAST_VALUE(theme_AGRICULTURE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_avg,
  LAST_VALUE(theme_ALLIANCE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_avg,
  LAST_VALUE(theme_DELAY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_avg,
  LAST_VALUE(theme_ECON_DEBT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_avg,
  LAST_VALUE(theme_ECON_INFLATION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_avg,
  LAST_VALUE(theme_ECON_STOCKMARKET_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_avg,
  LAST_VALUE(theme_ELECTION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_avg,
  LAST_VALUE(theme_EPU_POLICY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_avg,
  LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_avg,
  LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_avg,
  LAST_VALUE(theme_LEGISLATION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_avg,
  LAST_VALUE(theme_NATURAL_DISASTER_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_avg,
  LAST_VALUE(theme_TAX_DISEASE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_avg,
  LAST_VALUE(theme_WB_698_TRADE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_avg,
  LAST_VALUE(theme_AGRICULTURE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_negative,
  LAST_VALUE(theme_ALLIANCE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_negative,
  LAST_VALUE(theme_DELAY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_negative,
  LAST_VALUE(theme_ECON_DEBT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_negative,
  LAST_VALUE(theme_ECON_INFLATION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_negative,
  LAST_VALUE(theme_ECON_STOCKMARKET_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_negative,
  LAST_VALUE(theme_ELECTION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_negative,
  LAST_VALUE(theme_EPU_POLICY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_negative,
  LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_negative,
  LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_negative,
  LAST_VALUE(theme_LEGISLATION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_negative,
  LAST_VALUE(theme_NATURAL_DISASTER_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_negative,
  LAST_VALUE(theme_TAX_DISEASE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_negative,
  LAST_VALUE(theme_WB_698_TRADE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_negative,
  LAST_VALUE(theme_AGRICULTURE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_polarity,
  LAST_VALUE(theme_ALLIANCE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_polarity,
  LAST_VALUE(theme_DELAY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_polarity,
  LAST_VALUE(theme_ECON_DEBT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_polarity,
  LAST_VALUE(theme_ECON_INFLATION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_polarity,
  LAST_VALUE(theme_ECON_STOCKMARKET_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_polarity,
  LAST_VALUE(theme_ELECTION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_polarity,
  LAST_VALUE(theme_EPU_POLICY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_polarity,
  LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_polarity,
  LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_polarity,
  LAST_VALUE(theme_LEGISLATION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_polarity,
  LAST_VALUE(theme_NATURAL_DISASTER_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_polarity,
  LAST_VALUE(theme_TAX_DISEASE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_polarity,
  LAST_VALUE(theme_WB_698_TRADE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_polarity,
  LAST_VALUE(theme_AGRICULTURE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_positive,
  LAST_VALUE(theme_ALLIANCE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_positive,
  LAST_VALUE(theme_DELAY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_positive,
  LAST_VALUE(theme_ECON_DEBT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_positive,
  LAST_VALUE(theme_ECON_INFLATION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_positive,
  LAST_VALUE(theme_ECON_STOCKMARKET_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_positive,
  LAST_VALUE(theme_ELECTION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_positive,
  LAST_VALUE(theme_EPU_POLICY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_positive,
  LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_positive,
  LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_positive,
  LAST_VALUE(theme_LEGISLATION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_positive,
  LAST_VALUE(theme_NATURAL_DISASTER_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_positive,
  LAST_VALUE(theme_TAX_DISEASE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_positive,
  LAST_VALUE(theme_WB_698_TRADE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_positive

FROM with_data
ORDER BY commodity, article_date;

-- Verify results
SELECT
  COUNT(*) AS total_rows,
  COUNT(DISTINCT article_date) AS unique_dates,
  COUNT(DISTINCT commodity) AS unique_commodities,
  MIN(article_date) AS min_date,
  MAX(article_date) AS max_date
FROM commodity.silver.gdelt_wide_fillforward;
