# Databricks notebook source
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS commodity.silver.gdelt_wide_fillforward;
# MAGIC
# MAGIC CREATE TABLE commodity.silver.gdelt_wide_fillforward
# MAGIC USING DELTA
# MAGIC AS
# MAGIC WITH date_spine AS (
# MAGIC   SELECT EXPLODE(SEQUENCE(
# MAGIC     (SELECT MIN(article_date) FROM commodity.silver.gdelt_wide),
# MAGIC     CURRENT_DATE(),
# MAGIC     INTERVAL 1 DAY
# MAGIC   )) AS article_date
# MAGIC ),
# MAGIC commodities AS (
# MAGIC   SELECT DISTINCT commodity FROM commodity.silver.gdelt_wide
# MAGIC ),
# MAGIC complete_grid AS (
# MAGIC   SELECT d.article_date, c.commodity
# MAGIC   FROM date_spine d CROSS JOIN commodities c
# MAGIC ),
# MAGIC with_data AS (
# MAGIC   SELECT g.article_date, g.commodity,
# MAGIC     COALESCE(w.group_ALL_count, 0) AS group_ALL_count,
# MAGIC     COALESCE(w.group_CORE_count, 0) AS group_CORE_count,
# MAGIC     COALESCE(w.group_LOGISTICS_count, 0) AS group_LOGISTICS_count,
# MAGIC     COALESCE(w.group_MARKET_count, 0) AS group_MARKET_count,
# MAGIC     COALESCE(w.group_OTHER_count, 0) AS group_OTHER_count,
# MAGIC     COALESCE(w.group_POLICY_count, 0) AS group_POLICY_count,
# MAGIC     COALESCE(w.group_SUPPLY_count, 0) AS group_SUPPLY_count,
# MAGIC     COALESCE(w.group_TRADE_count, 0) AS group_TRADE_count,
# MAGIC     COALESCE(w.theme_AGRICULTURE_count, 0) AS theme_AGRICULTURE_count,
# MAGIC     COALESCE(w.theme_ALLIANCE_count, 0) AS theme_ALLIANCE_count,
# MAGIC     COALESCE(w.theme_DELAY_count, 0) AS theme_DELAY_count,
# MAGIC     COALESCE(w.theme_ECON_DEBT_count, 0) AS theme_ECON_DEBT_count,
# MAGIC     COALESCE(w.theme_ECON_INFLATION_count, 0) AS theme_ECON_INFLATION_count,
# MAGIC     COALESCE(w.theme_ECON_STOCKMARKET_count, 0) AS theme_ECON_STOCKMARKET_count,
# MAGIC     COALESCE(w.theme_ELECTION_count, 0) AS theme_ELECTION_count,
# MAGIC     COALESCE(w.theme_EPU_POLICY_count, 0) AS theme_EPU_POLICY_count,
# MAGIC     COALESCE(w.theme_EPU_POLICY_GOVERNMENT_count, 0) AS theme_EPU_POLICY_GOVERNMENT_count,
# MAGIC     COALESCE(w.theme_GENERAL_GOVERNMENT_count, 0) AS theme_GENERAL_GOVERNMENT_count,
# MAGIC     COALESCE(w.theme_LEGISLATION_count, 0) AS theme_LEGISLATION_count,
# MAGIC     COALESCE(w.theme_NATURAL_DISASTER_count, 0) AS theme_NATURAL_DISASTER_count,
# MAGIC     COALESCE(w.theme_TAX_DISEASE_count, 0) AS theme_TAX_DISEASE_count,
# MAGIC     COALESCE(w.theme_WB_698_TRADE_count, 0) AS theme_WB_698_TRADE_count,
# MAGIC     w.group_ALL_tone_avg, w.group_ALL_tone_positive, w.group_ALL_tone_negative, w.group_ALL_tone_polarity,
# MAGIC     w.group_CORE_tone_avg, w.group_LOGISTICS_tone_avg, w.group_MARKET_tone_avg, w.group_OTHER_tone_avg,
# MAGIC     w.group_POLICY_tone_avg, w.group_SUPPLY_tone_avg, w.group_TRADE_tone_avg,
# MAGIC     w.group_CORE_tone_negative, w.group_LOGISTICS_tone_negative, w.group_MARKET_tone_negative,
# MAGIC     w.group_OTHER_tone_negative, w.group_POLICY_tone_negative, w.group_SUPPLY_tone_negative, w.group_TRADE_tone_negative,
# MAGIC     w.group_CORE_tone_polarity, w.group_LOGISTICS_tone_polarity, w.group_MARKET_tone_polarity,
# MAGIC     w.group_OTHER_tone_polarity, w.group_POLICY_tone_polarity, w.group_SUPPLY_tone_polarity, w.group_TRADE_tone_polarity,
# MAGIC     w.group_CORE_tone_positive, w.group_LOGISTICS_tone_positive, w.group_MARKET_tone_positive,
# MAGIC     w.group_OTHER_tone_positive, w.group_POLICY_tone_positive, w.group_SUPPLY_tone_positive, w.group_TRADE_tone_positive,
# MAGIC     w.theme_AGRICULTURE_tone_avg, w.theme_ALLIANCE_tone_avg, w.theme_DELAY_tone_avg,
# MAGIC     w.theme_ECON_DEBT_tone_avg, w.theme_ECON_INFLATION_tone_avg, w.theme_ECON_STOCKMARKET_tone_avg,
# MAGIC     w.theme_ELECTION_tone_avg, w.theme_EPU_POLICY_tone_avg, w.theme_EPU_POLICY_GOVERNMENT_tone_avg,
# MAGIC     w.theme_GENERAL_GOVERNMENT_tone_avg, w.theme_LEGISLATION_tone_avg, w.theme_NATURAL_DISASTER_tone_avg,
# MAGIC     w.theme_TAX_DISEASE_tone_avg, w.theme_WB_698_TRADE_tone_avg,
# MAGIC     w.theme_AGRICULTURE_tone_negative, w.theme_ALLIANCE_tone_negative, w.theme_DELAY_tone_negative,
# MAGIC     w.theme_ECON_DEBT_tone_negative, w.theme_ECON_INFLATION_tone_negative, w.theme_ECON_STOCKMARKET_tone_negative,
# MAGIC     w.theme_ELECTION_tone_negative, w.theme_EPU_POLICY_tone_negative, w.theme_EPU_POLICY_GOVERNMENT_tone_negative,
# MAGIC     w.theme_GENERAL_GOVERNMENT_tone_negative, w.theme_LEGISLATION_tone_negative, w.theme_NATURAL_DISASTER_tone_negative,
# MAGIC     w.theme_TAX_DISEASE_tone_negative, w.theme_WB_698_TRADE_tone_negative,
# MAGIC     w.theme_AGRICULTURE_tone_polarity, w.theme_ALLIANCE_tone_polarity, w.theme_DELAY_tone_polarity,
# MAGIC     w.theme_ECON_DEBT_tone_polarity, w.theme_ECON_INFLATION_tone_polarity, w.theme_ECON_STOCKMARKET_tone_polarity,
# MAGIC     w.theme_ELECTION_tone_polarity, w.theme_EPU_POLICY_tone_polarity, w.theme_EPU_POLICY_GOVERNMENT_tone_polarity,
# MAGIC     w.theme_GENERAL_GOVERNMENT_tone_polarity, w.theme_LEGISLATION_tone_polarity, w.theme_NATURAL_DISASTER_tone_polarity,
# MAGIC     w.theme_TAX_DISEASE_tone_polarity, w.theme_WB_698_TRADE_tone_polarity,
# MAGIC     w.theme_AGRICULTURE_tone_positive, w.theme_ALLIANCE_tone_positive, w.theme_DELAY_tone_positive,
# MAGIC     w.theme_ECON_DEBT_tone_positive, w.theme_ECON_INFLATION_tone_positive, w.theme_ECON_STOCKMARKET_tone_positive,
# MAGIC     w.theme_ELECTION_tone_positive, w.theme_EPU_POLICY_tone_positive, w.theme_EPU_POLICY_GOVERNMENT_tone_positive,
# MAGIC     w.theme_GENERAL_GOVERNMENT_tone_positive, w.theme_LEGISLATION_tone_positive, w.theme_NATURAL_DISASTER_tone_positive,
# MAGIC     w.theme_TAX_DISEASE_tone_positive, w.theme_WB_698_TRADE_tone_positive
# MAGIC   FROM complete_grid g
# MAGIC   LEFT JOIN commodity.silver.gdelt_wide w ON g.article_date = w.article_date AND g.commodity = w.commodity
# MAGIC )
# MAGIC SELECT article_date, commodity,
# MAGIC   group_ALL_count, group_CORE_count, group_LOGISTICS_count, group_MARKET_count, group_OTHER_count,
# MAGIC   group_POLICY_count, group_SUPPLY_count, group_TRADE_count,
# MAGIC   theme_AGRICULTURE_count, theme_ALLIANCE_count, theme_DELAY_count, theme_ECON_DEBT_count,
# MAGIC   theme_ECON_INFLATION_count, theme_ECON_STOCKMARKET_count, theme_ELECTION_count, theme_EPU_POLICY_count,
# MAGIC   theme_EPU_POLICY_GOVERNMENT_count, theme_GENERAL_GOVERNMENT_count, theme_LEGISLATION_count,
# MAGIC   theme_NATURAL_DISASTER_count, theme_TAX_DISEASE_count, theme_WB_698_TRADE_count,
# MAGIC   LAST_VALUE(group_ALL_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_avg,
# MAGIC   LAST_VALUE(group_ALL_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_positive,
# MAGIC   LAST_VALUE(group_ALL_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_negative,
# MAGIC   LAST_VALUE(group_ALL_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_ALL_tone_polarity,
# MAGIC   LAST_VALUE(group_CORE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_avg,
# MAGIC   LAST_VALUE(group_LOGISTICS_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_avg,
# MAGIC   LAST_VALUE(group_MARKET_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_avg,
# MAGIC   LAST_VALUE(group_OTHER_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_avg,
# MAGIC   LAST_VALUE(group_POLICY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_avg,
# MAGIC   LAST_VALUE(group_SUPPLY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_avg,
# MAGIC   LAST_VALUE(group_TRADE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_avg,
# MAGIC   LAST_VALUE(group_CORE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_negative,
# MAGIC   LAST_VALUE(group_LOGISTICS_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_negative,
# MAGIC   LAST_VALUE(group_MARKET_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_negative,
# MAGIC   LAST_VALUE(group_OTHER_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_negative,
# MAGIC   LAST_VALUE(group_POLICY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_negative,
# MAGIC   LAST_VALUE(group_SUPPLY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_negative,
# MAGIC   LAST_VALUE(group_TRADE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_negative,
# MAGIC   LAST_VALUE(group_CORE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_polarity,
# MAGIC   LAST_VALUE(group_LOGISTICS_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_polarity,
# MAGIC   LAST_VALUE(group_MARKET_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_polarity,
# MAGIC   LAST_VALUE(group_OTHER_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_polarity,
# MAGIC   LAST_VALUE(group_POLICY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_polarity,
# MAGIC   LAST_VALUE(group_SUPPLY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_polarity,
# MAGIC   LAST_VALUE(group_TRADE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_polarity,
# MAGIC   LAST_VALUE(group_CORE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_CORE_tone_positive,
# MAGIC   LAST_VALUE(group_LOGISTICS_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_LOGISTICS_tone_positive,
# MAGIC   LAST_VALUE(group_MARKET_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_MARKET_tone_positive,
# MAGIC   LAST_VALUE(group_OTHER_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_OTHER_tone_positive,
# MAGIC   LAST_VALUE(group_POLICY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_POLICY_tone_positive,
# MAGIC   LAST_VALUE(group_SUPPLY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_SUPPLY_tone_positive,
# MAGIC   LAST_VALUE(group_TRADE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS group_TRADE_tone_positive,
# MAGIC   LAST_VALUE(theme_AGRICULTURE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_avg,
# MAGIC   LAST_VALUE(theme_ALLIANCE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_avg,
# MAGIC   LAST_VALUE(theme_DELAY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_avg,
# MAGIC   LAST_VALUE(theme_ECON_DEBT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_avg,
# MAGIC   LAST_VALUE(theme_ECON_INFLATION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_avg,
# MAGIC   LAST_VALUE(theme_ECON_STOCKMARKET_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_avg,
# MAGIC   LAST_VALUE(theme_ELECTION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_avg,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_avg,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_avg,
# MAGIC   LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_avg,
# MAGIC   LAST_VALUE(theme_LEGISLATION_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_avg,
# MAGIC   LAST_VALUE(theme_NATURAL_DISASTER_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_avg,
# MAGIC   LAST_VALUE(theme_TAX_DISEASE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_avg,
# MAGIC   LAST_VALUE(theme_WB_698_TRADE_tone_avg, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_avg,
# MAGIC   LAST_VALUE(theme_AGRICULTURE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_negative,
# MAGIC   LAST_VALUE(theme_ALLIANCE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_negative,
# MAGIC   LAST_VALUE(theme_DELAY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_negative,
# MAGIC   LAST_VALUE(theme_ECON_DEBT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_negative,
# MAGIC   LAST_VALUE(theme_ECON_INFLATION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_negative,
# MAGIC   LAST_VALUE(theme_ECON_STOCKMARKET_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_negative,
# MAGIC   LAST_VALUE(theme_ELECTION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_negative,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_negative,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_negative,
# MAGIC   LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_negative,
# MAGIC   LAST_VALUE(theme_LEGISLATION_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_negative,
# MAGIC   LAST_VALUE(theme_NATURAL_DISASTER_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_negative,
# MAGIC   LAST_VALUE(theme_TAX_DISEASE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_negative,
# MAGIC   LAST_VALUE(theme_WB_698_TRADE_tone_negative, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_negative,
# MAGIC   LAST_VALUE(theme_AGRICULTURE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_polarity,
# MAGIC   LAST_VALUE(theme_ALLIANCE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_polarity,
# MAGIC   LAST_VALUE(theme_DELAY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_polarity,
# MAGIC   LAST_VALUE(theme_ECON_DEBT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_polarity,
# MAGIC   LAST_VALUE(theme_ECON_INFLATION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_polarity,
# MAGIC   LAST_VALUE(theme_ECON_STOCKMARKET_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_polarity,
# MAGIC   LAST_VALUE(theme_ELECTION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_polarity,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_polarity,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_polarity,
# MAGIC   LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_polarity,
# MAGIC   LAST_VALUE(theme_LEGISLATION_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_polarity,
# MAGIC   LAST_VALUE(theme_NATURAL_DISASTER_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_polarity,
# MAGIC   LAST_VALUE(theme_TAX_DISEASE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_polarity,
# MAGIC   LAST_VALUE(theme_WB_698_TRADE_tone_polarity, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_polarity,
# MAGIC   LAST_VALUE(theme_AGRICULTURE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_AGRICULTURE_tone_positive,
# MAGIC   LAST_VALUE(theme_ALLIANCE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ALLIANCE_tone_positive,
# MAGIC   LAST_VALUE(theme_DELAY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_DELAY_tone_positive,
# MAGIC   LAST_VALUE(theme_ECON_DEBT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_DEBT_tone_positive,
# MAGIC   LAST_VALUE(theme_ECON_INFLATION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_INFLATION_tone_positive,
# MAGIC   LAST_VALUE(theme_ECON_STOCKMARKET_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ECON_STOCKMARKET_tone_positive,
# MAGIC   LAST_VALUE(theme_ELECTION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_ELECTION_tone_positive,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_tone_positive,
# MAGIC   LAST_VALUE(theme_EPU_POLICY_GOVERNMENT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_EPU_POLICY_GOVERNMENT_tone_positive,
# MAGIC   LAST_VALUE(theme_GENERAL_GOVERNMENT_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_GENERAL_GOVERNMENT_tone_positive,
# MAGIC   LAST_VALUE(theme_LEGISLATION_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_LEGISLATION_tone_positive,
# MAGIC   LAST_VALUE(theme_NATURAL_DISASTER_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_NATURAL_DISASTER_tone_positive,
# MAGIC   LAST_VALUE(theme_TAX_DISEASE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_TAX_DISEASE_tone_positive,
# MAGIC   LAST_VALUE(theme_WB_698_TRADE_tone_positive, TRUE) OVER (PARTITION BY commodity ORDER BY article_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS theme_WB_698_TRADE_tone_positive
# MAGIC FROM with_data
# MAGIC ORDER BY commodity, article_date;
